import testImg from "../assets/images/shampoo.jpg";

export const allGoods = [
  {
    id: 1,
    name: "BASE Professional / 🎁 🔥 Шампунь для волос профессиональный, 1 л",
    price: 370,
    img: testImg,
    color: ["white", "green"],
    country: "China",
    quantity: 11,
  },
  {
    id: 2,
    name: "BASE Professional / 🎁 🔥 Шампунь для волос профессиональный, 1 л",
    price: 370,
    img: testImg,
    color: ["white", "green"],
    country: "China",
    quantity: 11,
  },
  {
    id: 3,
    name: "BASE Professional / 🎁 🔥 Шампунь для волос профессиональный, 1 л",
    price: 370,
    img: testImg,
    color: ["white", "green"],
    country: "China",
    quantity: 11,
  },
  {
    id: 4,
    name: "BASE Professional / 🎁 🔥 Шампунь для волос профессиональный, 1 л",
    price: 370,
    img: testImg,
    color: ["white", "green"],
    country: "China",
    quantity: 11,
  },
  {
    id: 5,
    name: "BASE Professional / 🎁 🔥 Шампунь для волос профессиональный, 1 л",
    price: 370,
    img: testImg,
    color: ["white", "green"],
    country: "China",
    quantity: 11,
  },
  {
    id: 6,
    name: "BASE Professional / 🎁 🔥 Шампунь для волос профессиональный, 1 л",
    price: 370,
    img: testImg,
    color: ["white", "green"],
    country: "China",
    quantity: 11,
  },
  {
    id: 7,
    name: "BASE Professional / 🎁 🔥 Шампунь для волос профессиональный, 1 л",
    price: 370,
    img: testImg,
    color: ["white", "green"],
    country: "China",
    quantity: 11,
  },
  {
    id: 8,
    name: "BASE Professional / 🎁 🔥 Шампунь для волос профессиональный, 1 л",
    price: 370,
    img: testImg,
    color: ["white", "green"],
    country: "China",
    quantity: 11,
  },
  {
    id: 9,
    name: "BASE Professional / 🎁 🔥 Шампунь для волос профессиональный, 1 л",
    price: 370,
    img: testImg,
    color: ["white", "green"],
    country: "China",
    quantity: 11,
  },
  {
    id: 10,
    name: "BASE Professional / 🎁 🔥 Шампунь для волос профессиональный, 1 л",
    price: 370,
    img: testImg,
    color: ["white", "green"],
    country: "China",
    quantity: 11,
  },
  {
    id: 11,
    name: "BASE Professional / 🎁 🔥 Шампунь для волос профессиональный, 1 л",
    price: 370,
    img: testImg,
    color: ["white", "green"],
    country: "China",
    quantity: 11,
  },
  {
    id: 12,
    name: "BASE Professional / 🎁 🔥 Шампунь для волос профессиональный, 1 л",
    price: 370,
    img: testImg,
    color: ["white", "green"],
    country: "China",
    quantity: 11,
  },
  {
    id: 13,
    name: "BASE Professional / 🎁 🔥 Шампунь для волос профессиональный, 1 л",
    price: 370,
    img: testImg,
    color: ["white", "green"],
    country: "China",
    quantity: 11,
  },
  {
    id: 14,
    name: "BASE Professional / 🎁 🔥 Шампунь для волос профессиональный, 1 л",
    price: 370,
    img: testImg,
    color: ["white", "green"],
    country: "China",
    quantity: 11,
  },
  {
    id: 15,
    name: "BASE Professional / 🎁 🔥 Шампунь для волос профессиональный, 1 л",
    price: 370,
    img: testImg,
    color: ["white", "green"],
    country: "China",
    quantity: 11,
  },
  {
    id: 16,
    name: "BASE Professional / 🎁 🔥 Шампунь для волос профессиональный, 1 л",
    price: 370,
    img: testImg,
    color: ["white", "green"],
    country: "China",
    quantity: 11,
  },
  {
    id: 17,
    name: "BASE Professional / 🎁 🔥 Шампунь для волос профессиональный, 1 л",
    price: 370,
    img: testImg,
    color: ["white", "green"],
    country: "China",
    quantity: 11,
  },
  {
    id: 18,
    name: "BASE Professional / 🎁 🔥 Шампунь для волос профессиональный, 1 л",
    price: 370,
    img: testImg,
    color: ["white", "green"],
    country: "China",
    quantity: 11,
  },
  {
    id: 19,
    name: "BASE Professional / 🎁 🔥 Шампунь для волос профессиональный, 1 л",
    price: 370,
    img: testImg,
    color: ["white", "green"],
    country: "China",
    quantity: 11,
  },
  {
    id: 20,
    name: "BASE Professional / 🎁 🔥 Шампунь для волос профессиональный, 1 л",
    price: 370,
    img: testImg,
    color: ["white", "green"],
    country: "China",
    quantity: 11,
  },
];
